#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:

hour=0
minute=0

while [ $hour -le 24 ]
do
    echo "Hour: $hour"
    while [ $minute -lt 60 ]
    do
        echo "$minute"
        (( minute++ ))
    done
    (( minute=0 ))
    (( hour++ ))
done
