#!/usr/bin/env bash
FILE="school"

if [ -e $FILE ]
then
	echo "$FILE exists"
	if [ -f $FILE ]
	then
		echo "$FILE is a regular file"
	fi
	if [ -s $FILE ]
	then
		echo "$FILE is not empty"
	else
		echo "$FILE is empty"
	fi
else
	echo "school file does not exist"
fi
